version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql # make relative links (eg. ./)?
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: yii2basic
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    networks:
      - my-network
  redis:                            # 可以隨意命名，通常以有意義的字串命名
    image: redis:5.0.5-alpine       # 服務容器，若無指定版號表示使用 latest 版本， alpine 容器佔用空間較小，通常建議使用
    ports:
      - '11211:11211'
    networks:
      - my-network
  php:
    # environment:
    #   - uid=UID
    #   - gid=GID
    user: ${CURRENT_UID}
    depends_on:
      - db
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8008:80'
    networks:
      - my-network
      
networks:
  my-network:
    name: my-app-network